VINS MONO COMMENTED: camodocal::Camera Class Reference
camodocal::Camera Class Reference abstract
base class for all camera model
#include <Camera.h>
Classes
class Parameters
nested class for camera parameters
Public Types
enum ModelType { KANNALA_BRANDT, MEI, PINHOLE, SCARAMUZZA }
enumerate variable of camera model
Public Member Functions
virtual ModelType modelType (void) const =0
virtual type of function modelType
virtual const std::string & cameraName (void) const =0
virtual type of funtion cameraName
virtual int imageWidth (void) const =0
virtual type of function imageWidth
virtual int imageHeight (void) const =0
virtual type of function imageHeight
virtual cv::Mat & mask (void)
virtual function of image Mask
virtual const cv::Mat & mask (void) const
virtual function of image Mask
virtual void estimateIntrinsics (const cv::Size &boardSize, const std::vector< std::vector< cv::Point3f > > &objectPoints, const std::vector< std::vector< cv::Point2f > > &imagePoints)=0
virtual function of camera intrinsics
virtual void estimateExtrinsics (const std::vector< cv::Point3f > &objectPoints, const std::vector< cv::Point2f > &imagePoints, cv::Mat &rvec, cv::Mat &tvec) const
calculate extrinsics with unit intrinsics
virtual void liftSphere (const Eigen::Vector2d &p, Eigen::Vector3d &P) const =0
Lift points from the image plane to the sphere.
virtual void liftProjective (const Eigen::Vector2d &p, Eigen::Vector3d &P) const =0
Lift points from the image plane to the projective space.
virtual void spaceToPlane (const Eigen::Vector3d &P, Eigen::Vector2d &p) const =0
Projects 3D points to the image plane (Pi function)
virtual void undistToPlane (const Eigen::Vector2d &p_u, Eigen::Vector2d &p) const =0
virtual cv::Mat initUndistortRectifyMap (cv::Mat &map1, cv::Mat &map2, float fx=-1.0f, float fy=-1.0f, cv::Size imageSize=cv::Size(0, 0), float cx=-1.0f, float cy=-1.0f, cv::Mat rmat=cv::Mat::eye(3, 3, CV_32F)) const =0
virtual int parameterCount (void) const =0
pure virtual function of parameter count
virtual void readParameters (const std::vector< double > &parameters)=0
pure virtual function of reading parameters
virtual void writeParameters (std::vector< double > &parameters) const =0
pure virtual function of writing parameters
virtual void writeParametersToYamlFile (const std::string &filename) const =0
pure virtual function of writing parameters to YAML file
virtual std::string parametersToString (void) const =0
pure virtual of converting parameters to string
double reprojectionDist (const Eigen::Vector3d &P1, const Eigen::Vector3d &P2) const
Calculates the reprojection distance between points.
double reprojectionError (const std::vector< std::vector< cv::Point3f > > &objectPoints, const std::vector< std::vector< cv::Point2f > > &imagePoints, const std::vector< cv::Mat > &rvecs, const std::vector< cv::Mat > &tvecs, cv::OutputArray perViewErrors=cv::noArray()) const
calculate average reprojection error of all points in all frames (total error divede by total points) with 3D points and 2D points
double reprojectionError (const Eigen::Vector3d &P, const Eigen::Quaterniond &camera_q, const Eigen::Vector3d &camera_t, const Eigen::Vector2d &observed_p) const
calculate reprojection error of one 3D point with camera pose P & Q
void projectPoints (const std::vector< cv::Point3f > &objectPoints, const cv::Mat &rvec, const cv::Mat &tvec, std::vector< cv::Point2f > &imagePoints) const
project 3D points to 2d plane
Protected Attributes
cv::Mat m_mask
image mask
Detailed Description
base class for all camera model
Member Function Documentation
estimateExtrinsics()
void camodocal::Camera::estimateExtrinsics (const std::vector< cv::Point3f > & objectPoints, const std::vector< cv::Point2f > & imagePoints, cv::Mat & rvec, cv::Mat & tvec) const virtual
calculate extrinsics with unit intrinsics
Parameters
objectPoints 3D points on object
imagePoints 2D point on image plane
rvec rotation vector
tvec transformation vector
References liftProjective().
Referenced by camodocal::CataCamera::estimateIntrinsics(), and camodocal::EquidistantCamera::estimateIntrinsics().
projectPoints()
void camodocal::Camera::projectPoints (const std::vector< cv::Point3f > & objectPoints, const cv::Mat & rvec, const cv::Mat & tvec, std::vector< cv::Point2f > & imagePoints) const
project 3D points to 2d plane
Parameters
objectPoints
rvec
tvec
imagePoints
reserve space for imagePoints according to objectPoints
convert from rotation vector to rotation matrix
References spaceToPlane().
Referenced by reprojectionError().
reprojectionDist()
double camodocal::Camera::reprojectionDist (const Eigen::Vector3d & P1, const Eigen::Vector3d & P2) const
Calculates the reprojection distance between points.
Parameters
P1 first 3D point coordinates
P2 second 3D point coordinates
Returns
euclidean distance in the plane
References spaceToPlane().
reprojectionError() [1/2]
double camodocal::Camera::reprojectionError (const std::vector< std::vector< cv::Point3f > > & objectPoints, const std::vector< std::vector< cv::Point2f > > & imagePoints, const std::vector< cv::Mat > & rvecs, const std::vector< cv::Mat > & tvecs, cv::OutputArray perViewErrors = cv::noArray()) const
calculate average reprojection error of all points in all frames (total error divede by total points) with 3D points and 2D points
Parameters
objectPoints 3D coordinates of object points
imagePoints 2D coordinates of image points
rvecs rotation vectors
tvecs transformation vectors
perViewErrors
Returns
:
count of image frames
current points in all image frames
check whether preVireError needed to be computed
imageCount * 1
using getMat() to convert from cv::OutputArray to cv::Mat
project points of frame i to image plane
calculate repeojection error of frame i()
calculate average reprojection error of frame i
return average reprojection error
References projectPoints().
Referenced by camodocal::CataCamera::estimateIntrinsics(), and camodocal::EquidistantCamera::estimateIntrinsics().
reprojectionError() [2/2]
double camodocal::Camera::reprojectionError (const Eigen::Vector3d & P, const Eigen::Quaterniond & camera_q, const Eigen::Vector3d & camera_t, const Eigen::Vector2d & observed_p) const
calculate reprojection error of one 3D point with camera pose P & Q
Parameters
P 3D coordinates of point
camera_q quaternion of camera pose
camera_t translation of camera pose
observed_p corresponding image point
Returns
:
References spaceToPlane().
The documentation for this class was generated from the following files:
camera_model/include/camodocal/camera_models/Camera.h
camera_model/src/camera_models/Camera.cc