VINS MONO COMMENTED: DBoW2::Result Class Reference
DBoW2::Result Class Reference
Single result of a query.
#include <QueryResults.h>
Public Member Functions
Result ()
debug
Result (EntryId _id, double _score)
bool operator< (const Result &r) const
bool operator> (const Result &r) const
bool operator== (EntryId id) const
bool operator< (double s) const
bool operator> (double s) const
Static Public Member Functions
static bool gt (const Result &a, const Result &b)
static bool ge (const Result &a, const Result &b)
static bool geq (const Result &a, const Result &b)
static bool geqv (const Result &a, double s)
static bool ltId (const Result &a, const Result &b)
Public Attributes
EntryId Id
Entry id.
double Score
Score obtained.
int nWords
debug
double bhatScore
double chiScore
double sumCommonVi
debug
double sumCommonWi
double expectedChiScore
Friends
std::ostream & operator<< (std::ostream &os, const Result &ret)
Detailed Description
Single result of a query.
Constructor & Destructor Documentation
Result() [1/2]
DBoW2::Result::Result () inline
debug
Empty constructors
Result() [2/2]
DBoW2::Result::Result (EntryId _id, double _score) inline
Creates a result with the given data
Parameters
_id entry id
_score score
Member Function Documentation
ge()
static bool DBoW2::Result::ge (const Result & a, const Result & b) inline static
Compares the scores of two results
Returns
true iff a.Score > b.Score
References Score.
geq()
static bool DBoW2::Result::geq (const Result & a, const Result & b) inline static
Returns true iff a.Score >= b.Score
Parameters
a
b
Returns
true iff a.Score >= b.Score
References Score.
geqv()
static bool DBoW2::Result::geqv (const Result & a, double s) inline static
Returns true iff a.Score >= s
Parameters
a
s
Returns
true iff a.Score >= s
References Score.
gt()
static bool DBoW2::Result::gt (const Result & a, const Result & b) inline static
Compares the score of two results
Parameters
a
b
Returns
true iff a.Score > b.Score
References Score.
Referenced by DBoW2::TemplatedDatabase< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::queryBhattacharyya(), and DBoW2::TemplatedDatabase< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::queryDotProduct().
ltId()
static bool DBoW2::Result::ltId (const Result & a, const Result & b) inline static
Returns true iff a.Id < b.Id
Parameters
a
b
Returns
true iff a.Id < b.Id
References Id, and operator<<.
operator<() [1/2]
bool DBoW2::Result::operator< (const Result & r) const inline
Compares the scores of two results
Returns
true iff this.score < r.score
References Score.
operator<() [2/2]
bool DBoW2::Result::operator< (double s) const inline
Compares the score of this entry with a given one
Parameters
s score to compare with
Returns
true iff this score < s
operator==()
bool DBoW2::Result::operator== (EntryId id) const inline
Compares the entry id of the result
Returns
true iff this.id == id
operator>() [1/2]
bool DBoW2::Result::operator> (const Result & r) const inline
Compares the scores of two results
Returns
true iff this.score > r.score
References Score.
operator>() [2/2]
bool DBoW2::Result::operator> (double s) const inline
Compares the score of this entry with a given one
Parameters
s score to compare with
Returns
true iff this score > s
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Result & ret) friend
Prints a string version of the result
Parameters
os ostream
ret Result to print
Referenced by ltId().
The documentation for this class was generated from the following file:
pose_graph/src/ThirdParty/DBoW/QueryResults.h