VINS MONO COMMENTED: camodocal::Camera::Parameters Class Reference
camodocal::Camera::Parameters Class Reference abstract
nested class for camera parameters
#include <Camera.h>
Public Member Functions
EIGEN_MAKE_ALIGNED_OPERATOR_NEW Parameters (ModelType modelType)
Construct a new Parameters object.
Parameters (ModelType modelType, const std::string &cameraName, int w, int h)
Construct a new Parameters object.
ModelType & modelType (void)
return modelType of current camera object
std::string & cameraName (void)
return name of current camera object
int & imageWidth (void)
return image width of current camera object
int & imageHeight (void)
return image height of current camera object
ModelType modelType (void) const
return modelType of current camera object (const data member)
const std::string & cameraName (void) const
return name of current camera object(const data member)
int imageWidth (void) const
return image width of current camera object(const data member)
int imageHeight (void) const
return image height of current camera object (const data member)
int nIntrinsics (void) const
return number of camera intrinsics(const data member)
virtual bool readFromYamlFile (const std::string &filename)=0
read parameters from YAML or XML file, (pure virtual function which must be override in son classes, following virtual function with '=0' are all pure virtual function)
virtual void writeToYamlFile (const std::string &filename) const =0
write parameters to YAML or XML file;
Protected Attributes
ModelType m_modelType
int m_nIntrinsics
std::string m_cameraName
camera name
int m_imageWidth
image width in pixels
int m_imageHeight
image height in pixels
Detailed Description
nested class for camera parameters
Constructor & Destructor Documentation
Parameters() [1/2]
camodocal::Camera::Parameters::Parameters (ModelType modelType)
Construct a new Parameters object.
Parameters
modelType model of current camera object
References m_nIntrinsics.
Parameters() [2/2]
camodocal::Camera::Parameters::Parameters (ModelType modelType, const std::string & cameraName, int w, int h)
Construct a new Parameters object.
Parameters
modelType model of current camera object
cameraName name of current camera object
w image width of current camera object
h image height of current camera object
References m_nIntrinsics.
Member Function Documentation
cameraName() [1/2]
std::string & camodocal::Camera::Parameters::cameraName (void)
return name of current camera object
Returns
:
Return values
cameraName std::string type
References m_cameraName.
Referenced by camodocal::OCAMCamera::cameraName(), camodocal::PinholeCamera::cameraName(), camodocal::EquidistantCamera::cameraName(), camodocal::CataCamera::cameraName(), camodocal::EquidistantCamera::estimateIntrinsics(), camodocal::CataCamera::estimateIntrinsics(), camodocal::CameraFactory::generateCamera(), and camodocal::PinholeCamera::Parameters::Parameters().
cameraName() [2/2]
const std::string & camodocal::Camera::Parameters::cameraName (void) const
return name of current camera object(const data member)
Returns
:
Return values
cameraName std::string type
References m_cameraName.
imageHeight() [1/2]
int & camodocal::Camera::Parameters::imageHeight (void)
return image height of current camera object
Returns
:
Return values
imageHeight image height in pixels, int type
References m_imageHeight.
Referenced by camodocal::PinholeCamera::distortion(), camodocal::CataCamera::distortion(), camodocal::OCAMCamera::estimateIntrinsics(), camodocal::PinholeCamera::estimateIntrinsics(), camodocal::CataCamera::estimateIntrinsics(), camodocal::EquidistantCamera::estimateIntrinsics(), camodocal::CameraFactory::generateCamera(), camodocal::OCAMCamera::imageHeight(), camodocal::PinholeCamera::imageHeight(), camodocal::EquidistantCamera::imageHeight(), camodocal::CataCamera::imageHeight(), camodocal::OCAMCamera::undistToPlane(), and camodocal::EquidistantCamera::undistToPlane().
imageHeight() [2/2]
int camodocal::Camera::Parameters::imageHeight (void) const
return image height of current camera object (const data member)
Returns
:
Return values
imageHeight image height in pixels, int type
References m_imageHeight.
imageWidth() [1/2]
int & camodocal::Camera::Parameters::imageWidth (void)
return image width of current camera object
Returns
:
Return values
imageWidth image width in pixels, int type
References m_imageWidth.
Referenced by camodocal::PinholeCamera::distortion(), camodocal::CataCamera::distortion(), camodocal::OCAMCamera::estimateIntrinsics(), camodocal::PinholeCamera::estimateIntrinsics(), camodocal::CataCamera::estimateIntrinsics(), camodocal::EquidistantCamera::estimateIntrinsics(), camodocal::CameraFactory::generateCamera(), camodocal::OCAMCamera::imageWidth(), camodocal::PinholeCamera::imageWidth(), camodocal::EquidistantCamera::imageWidth(), camodocal::CataCamera::imageWidth(), camodocal::OCAMCamera::undistToPlane(), and camodocal::EquidistantCamera::undistToPlane().
imageWidth() [2/2]
int camodocal::Camera::Parameters::imageWidth (void) const
return image width of current camera object(const data member)
Returns
:
Return values
imageWidth image width in pixels, int type
References m_imageWidth.
modelType() [1/2]
Camera::ModelType & camodocal::Camera::Parameters::modelType (void)
return modelType of current camera object
Returns
:
Return values
modelType modelType of current camera object
Referenced by camodocal::OCAMCamera::modelType(), camodocal::PinholeCamera::modelType(), camodocal::CataCamera::modelType(), and camodocal::EquidistantCamera::modelType().
modelType() [2/2]
Camera::ModelType camodocal::Camera::Parameters::modelType (void) const
return modelType of current camera object (const data member)
Returns
:
Return values
modelType modelType of current camera object
nIntrinsics()
int camodocal::Camera::Parameters::nIntrinsics (void) const
return number of camera intrinsics(const data member)
Returns
:
Return values
nIntrinsics number of intrinsics, int type
References m_nIntrinsics.
readFromYamlFile()
virtual bool camodocal::Camera::Parameters::readFromYamlFile (const std::string & filename) pure virtual
read parameters from YAML or XML file, (pure virtual function which must be override in son classes, following virtual function with '=0' are all pure virtual function)
Parameters
filename filename of YAML or XML file
Implemented in camodocal::CataCamera::Parameters, camodocal::OCAMCamera::Parameters, camodocal::EquidistantCamera::Parameters, and camodocal::PinholeCamera::Parameters.
writeToYamlFile()
virtual void camodocal::Camera::Parameters::writeToYamlFile (const std::string & filename) const pure virtual
write parameters to YAML or XML file;
Parameters
filename filename of YAML of XML file
Implemented in camodocal::CataCamera::Parameters, camodocal::OCAMCamera::Parameters, camodocal::EquidistantCamera::Parameters, and camodocal::PinholeCamera::Parameters.
Member Data Documentation
m_nIntrinsics
int camodocal::Camera::Parameters::m_nIntrinsics protected
number of camera Intrinsics, for pinhole camera model are four distortion parameters: k1, k2, p1, p2 four projection parameters: fx, fy, cx, cy
Referenced by nIntrinsics(), and Parameters().
The documentation for this class was generated from the following files:
camera_model/include/camodocal/camera_models/Camera.h
camera_model/src/camera_models/Camera.cc