VINS MONO COMMENTED: camodocal::CameraFactory Class Reference
camodocal::CameraFactory Class Reference
Public Member Functions
CameraPtr generateCamera (Camera::ModelType modelType, const std::string &cameraName, cv::Size imageSize) const
generate Camera object according to modelType
CameraPtr generateCameraFromYamlFile (const std::string &filename)
generate camera object according to YAML file
Static Public Member Functions
static boost::shared_ptr< CameraFactory > instance (void)
Get point of cameraFactory.
Member Function Documentation
generateCamera()
CameraPtr camodocal::CameraFactory::generateCamera (Camera::ModelType modelType, const std::string & cameraName, cv::Size imageSize) const
generate Camera object according to modelType
Parameters
modelType camera model
cameraName camera name
imageSize image Size
Returns
: shared_ptr of camera
References camodocal::Camera::Parameters::cameraName(), camodocal::Camera::Parameters::imageHeight(), and camodocal::Camera::Parameters::imageWidth().
generateCameraFromYamlFile()
CameraPtr camodocal::CameraFactory::generateCameraFromYamlFile (const std::string & filename)
generate camera object according to YAML file
Parameters
filename name of YAML file
Returns
: shared_ptr of camera
References camodocal::PinholeCamera::Parameters::readFromYamlFile(), camodocal::EquidistantCamera::Parameters::readFromYamlFile(), camodocal::OCAMCamera::Parameters::readFromYamlFile(), and camodocal::CataCamera::Parameters::readFromYamlFile().
instance()
boost::shared_ptr< CameraFactory > camodocal::CameraFactory::instance (void) static
Get point of cameraFactory.
Returns
: shared_ptr of CameraFactory
The documentation for this class was generated from the following files:
camera_model/include/camodocal/camera_models/CameraFactory.h
camera_model/src/camera_models/CameraFactory.cc