VINS MONO COMMENTED: DBoW2::TemplatedVocabulary< TDescriptor, F > Class Template Reference
DBoW2::TemplatedVocabulary< TDescriptor, F > Class Template Reference
Generic Vocabulary.
#include <TemplatedVocabulary.h>
Classes
struct Node
Tree node.
Public Member Functions
TemplatedVocabulary (int k=10, int L=5, WeightingType weighting=TF_IDF, ScoringType scoring=L1_NORM)
TemplatedVocabulary (const std::string &filename)
TemplatedVocabulary (const char *filename)
TemplatedVocabulary (const TemplatedVocabulary< TDescriptor, F > &voc)
virtual ~TemplatedVocabulary ()
TemplatedVocabulary< TDescriptor, F > & operator= (const TemplatedVocabulary< TDescriptor, F > &voc)
virtual void create (const std::vector< std::vector< TDescriptor > > &training_features)
virtual void create (const std::vector< std::vector< TDescriptor > > &training_features, int k, int L)
virtual void create (const std::vector< std::vector< TDescriptor > > &training_features, int k, int L, WeightingType weighting, ScoringType scoring)
virtual unsigned int size () const
virtual bool empty () const
virtual void transform (const std::vector< TDescriptor > &features, BowVector &v) const
virtual void transform (const std::vector< TDescriptor > &features, BowVector &v, FeatureVector &fv, int levelsup) const
virtual WordId transform (const TDescriptor &feature) const
double score (const BowVector &a, const BowVector &b) const
virtual NodeId getParentNode (WordId wid, int levelsup) const
void getWordsFromNode (NodeId nid, std::vector< WordId > &words) const
int getBranchingFactor () const
int getDepthLevels () const
float getEffectiveLevels () const
virtual TDescriptor getWord (WordId wid) const
virtual WordValue getWordWeight (WordId wid) const
WeightingType getWeightingType () const
ScoringType getScoringType () const
void setWeightingType (WeightingType type)
void setScoringType (ScoringType type)
void save (const std::string &filename) const
void load (const std::string &filename)
virtual void save (cv::FileStorage &fs, const std::string &name="vocabulary") const
virtual void load (const cv::FileStorage &fs, const std::string &name="vocabulary")
virtual void loadBin (const std::string &filename)
virtual int stopWords (double minWeight)
Protected Types
typedef const TDescriptor * pDescriptor
Pointer to descriptor.
Protected Member Functions
void createScoringObject ()
void getFeatures (const std::vector< std::vector< TDescriptor > > &training_features, std::vector< pDescriptor > &features) const
virtual void transform (const TDescriptor &feature, WordId &id, WordValue &weight, NodeId *nid=NULL, int levelsup=0) const
virtual void transform (const TDescriptor &feature, WordId &id) const
void HKmeansStep (NodeId parent_id, const std::vector< pDescriptor > &descriptors, int current_level)
virtual void initiateClusters (const std::vector< pDescriptor > &descriptors, std::vector< TDescriptor > &clusters) const
void initiateClustersKMpp (const std::vector< pDescriptor > &descriptors, std::vector< TDescriptor > &clusters) const
void createWords ()
void setNodeWeights (const std::vector< std::vector< TDescriptor > > &features)
Protected Attributes
int m_k
Branching factor.
int m_L
Depth levels.
WeightingType m_weighting
Weighting method.
ScoringType m_scoring
Scoring method.
GeneralScoring * m_scoring_object
Object for computing scores.
std::vector< Node > m_nodes
Tree nodes.
std::vector< Node * > m_words
Detailed Description
template<class TDescriptor, class F>
class DBoW2::TemplatedVocabulary< TDescriptor, F >
Generic Vocabulary.
Parameters
TDescriptor class of descriptor
F class of descriptor functions
Constructor & Destructor Documentation
TemplatedVocabulary() [1/4]
template<class TDescriptor , class F > DBoW2::TemplatedVocabulary< TDescriptor, F >::TemplatedVocabulary (int k = 10, int L = 5, WeightingType weighting = TF_IDF, ScoringType scoring = L1_NORM)
Initiates an empty vocabulary
Parameters
k branching factor
L depth levels
weighting weighting type
scoring scoring type
Referenced by DBoW2::TemplatedVocabulary< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::TemplatedVocabulary().
TemplatedVocabulary() [2/4]
template<class TDescriptor , class F > DBoW2::TemplatedVocabulary< TDescriptor, F >::TemplatedVocabulary (const std::string & filename)
Creates the vocabulary by loading a file
Parameters
filename
TemplatedVocabulary() [3/4]
template<class TDescriptor , class F > DBoW2::TemplatedVocabulary< TDescriptor, F >::TemplatedVocabulary (const char * filename)
Creates the vocabulary by loading a file
Parameters
filename
TemplatedVocabulary() [4/4]
template<class TDescriptor, class F> DBoW2::TemplatedVocabulary< TDescriptor, F >::TemplatedVocabulary (const TemplatedVocabulary< TDescriptor, F > & voc)
Copy constructor
Parameters
voc
~TemplatedVocabulary()
template<class TDescriptor , class F > DBoW2::TemplatedVocabulary< TDescriptor, F >::~TemplatedVocabulary () virtual
Destructor
Member Function Documentation
create() [1/3]
template<class TDescriptor, class F > void DBoW2::TemplatedVocabulary< TDescriptor, F >::create (const std::vector< std::vector< TDescriptor > > & training_features) virtual
Creates a vocabulary from the training features with the already defined parameters
Parameters
training_features
create() [2/3]
template<class TDescriptor, class F > void DBoW2::TemplatedVocabulary< TDescriptor, F >::create (const std::vector< std::vector< TDescriptor > > & training_features, int k, int L) virtual
Creates a vocabulary from the training features, setting the branching factor and the depth levels of the tree
Parameters
training_features
k branching factor
L depth levels
create() [3/3]
template<class TDescriptor, class F > void DBoW2::TemplatedVocabulary< TDescriptor, F >::create (const std::vector< std::vector< TDescriptor > > & training_features, int k, int L, WeightingType weighting, ScoringType scoring) virtual
Creates a vocabulary from the training features, setting the branching factor nad the depth levels of the tree, and the weighting and scoring schemes
createScoringObject()
template<class TDescriptor , class F > void DBoW2::TemplatedVocabulary< TDescriptor, F >::createScoringObject () protected
Creates an instance of the scoring object accoring to m_scoring
Referenced by DBoW2::TemplatedVocabulary< TDescriptor, F >::Node::isLeaf(), DBoW2::TemplatedVocabulary< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::setScoringType(), and DBoW2::TemplatedVocabulary< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::TemplatedVocabulary().
createWords()
template<class TDescriptor , class F > void DBoW2::TemplatedVocabulary< TDescriptor, F >::createWords () protected
Create the words of the vocabulary once the tree has been built
Referenced by DBoW2::TemplatedVocabulary< TDescriptor, F >::Node::isLeaf().
empty()
template<class TDescriptor , class F > bool DBoW2::TemplatedVocabulary< TDescriptor, F >::empty () const inline virtual
Returns whether the vocabulary is empty (i.e. it has not been trained)
Returns
true iff the vocabulary is empty
Referenced by DBoW2::TemplatedVocabulary< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::empty().
getBranchingFactor()
template<class TDescriptor, class F> int DBoW2::TemplatedVocabulary< TDescriptor, F >::getBranchingFactor () const inline
Returns the branching factor of the tree (k)
Returns
k
Referenced by DBoW2::operator<<().
getDepthLevels()
template<class TDescriptor, class F> int DBoW2::TemplatedVocabulary< TDescriptor, F >::getDepthLevels () const inline
Returns the depth levels of the tree (L)
Returns
L
Referenced by DBoW2::operator<<().
getEffectiveLevels()
template<class TDescriptor , class F > float DBoW2::TemplatedVocabulary< TDescriptor, F >::getEffectiveLevels () const
Returns the real depth levels of the tree on average
Returns
average of depth levels of leaves
Referenced by DBoW2::TemplatedVocabulary< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::getDepthLevels().
getFeatures()
template<class TDescriptor, class F > void DBoW2::TemplatedVocabulary< TDescriptor, F >::getFeatures (const std::vector< std::vector< TDescriptor > > & training_features, std::vector< pDescriptor > & features) const protected
Returns a set of pointers to descriptores
Parameters
training_features all the features
features (out) pointers to the training features
Referenced by DBoW2::TemplatedVocabulary< TDescriptor, F >::Node::isLeaf().
getParentNode()
template<class TDescriptor , class F > NodeId DBoW2::TemplatedVocabulary< TDescriptor, F >::getParentNode (WordId wid, int levelsup) const virtual
Returns the id of the node that is "levelsup" levels from the word given
Parameters
wid word id
levelsup 0..L
Returns
node id. if levelsup is 0, returns the node id associated to the word id
getScoringType()
template<class TDescriptor, class F> ScoringType DBoW2::TemplatedVocabulary< TDescriptor, F >::getScoringType () const inline
Returns the scoring method
Returns
scoring method
Referenced by DBoW2::operator<<().
getWeightingType()
template<class TDescriptor, class F> WeightingType DBoW2::TemplatedVocabulary< TDescriptor, F >::getWeightingType () const inline
Returns the weighting method
Returns
weighting method
Referenced by DBoW2::operator<<().
getWord()
template<class TDescriptor , class F > TDescriptor DBoW2::TemplatedVocabulary< TDescriptor, F >::getWord (WordId wid) const inline virtual
Returns the descriptor of a word
Parameters
wid word id
Returns
descriptor
Referenced by DBoW2::TemplatedVocabulary< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::getDepthLevels().
getWordsFromNode()
template<class TDescriptor , class F > void DBoW2::TemplatedVocabulary< TDescriptor, F >::getWordsFromNode (NodeId nid, std::vector< WordId > & words) const
Returns the ids of all the words that are under the given node id, by traversing any of the branches that goes down from the node
Parameters
nid starting node id
words ids of words
getWordWeight()
template<class TDescriptor , class F > WordValue DBoW2::TemplatedVocabulary< TDescriptor, F >::getWordWeight (WordId wid) const inline virtual
Returns the weight of a word
Parameters
wid word id
Returns
weight
Referenced by DBoW2::TemplatedVocabulary< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::getDepthLevels().
HKmeansStep()
template<class TDescriptor , class F > void DBoW2::TemplatedVocabulary< TDescriptor, F >::HKmeansStep (NodeId parent_id, const std::vector< pDescriptor > & descriptors, int current_level) protected
Creates a level in the tree, under the parent, by running kmeans with a descriptor set, and recursively creates the subsequent levels too
Parameters
parent_id id of parent node
descriptors descriptors to run the kmeans on
current_level current level in the tree
Referenced by DBoW2::TemplatedVocabulary< TDescriptor, F >::Node::isLeaf().
initiateClusters()
template<class TDescriptor, class F > void DBoW2::TemplatedVocabulary< TDescriptor, F >::initiateClusters (const std::vector< pDescriptor > & descriptors, std::vector< TDescriptor > & clusters) const protected virtual
Creates k clusters from the given descriptors with some seeding algorithm.
Note
In this class, kmeans++ is used, but this function should be overriden by inherited classes.
Referenced by DBoW2::TemplatedVocabulary< TDescriptor, F >::Node::isLeaf().
initiateClustersKMpp()
template<class TDescriptor, class F > void DBoW2::TemplatedVocabulary< TDescriptor, F >::initiateClustersKMpp (const std::vector< pDescriptor > & descriptors, std::vector< TDescriptor > & clusters) const protected
Creates k clusters from the given descriptor sets by running the initial step of kmeans++
Parameters
descriptors
clusters resulting clusters
Referenced by DBoW2::TemplatedVocabulary< TDescriptor, F >::Node::isLeaf().
load() [1/2]
template<class TDescriptor , class F > void DBoW2::TemplatedVocabulary< TDescriptor, F >::load (const std::string & filename)
Loads the vocabulary from a file
Parameters
filename
Referenced by DBoW2::TemplatedVocabulary< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::getScoringType().
load() [2/2]
template<class TDescriptor , class F > void DBoW2::TemplatedVocabulary< TDescriptor, F >::load (const cv::FileStorage & fs, const std::string & name = "vocabulary") virtual
Loads the vocabulary from a file storage node
Parameters
fn first node
subname name of the child node of fn where the tree is stored. If not given, the fn node is used instead
operator=()
template<class TDescriptor, class F> TemplatedVocabulary< TDescriptor, F > & DBoW2::TemplatedVocabulary< TDescriptor, F >::operator= (const TemplatedVocabulary< TDescriptor, F > & voc)
Assigns the given vocabulary to this by copying its data and removing all the data contained by this vocabulary before
Parameters
voc
Returns
reference to this vocabulary
save() [1/2]
template<class TDescriptor , class F > void DBoW2::TemplatedVocabulary< TDescriptor, F >::save (const std::string & filename) const
Saves the vocabulary into a file
Parameters
filename
Referenced by DBoW2::TemplatedVocabulary< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::getScoringType().
save() [2/2]
template<class TDescriptor , class F > void DBoW2::TemplatedVocabulary< TDescriptor, F >::save (cv::FileStorage & fs, const std::string & name = "vocabulary") const virtual
Saves the vocabulary to a file storage structure
Parameters
fn node in file storage
score()
template<class TDescriptor , class F > double DBoW2::TemplatedVocabulary< TDescriptor, F >::score (const BowVector & a, const BowVector & b) const inline
Returns the score of two vectors
Parameters
a vector
b vector
Returns
score between vectors
Note
the vectors must be already sorted and normalized if necessary
Referenced by DBoW2::TemplatedVocabulary< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::score().
setNodeWeights()
template<class TDescriptor, class F > void DBoW2::TemplatedVocabulary< TDescriptor, F >::setNodeWeights (const std::vector< std::vector< TDescriptor > > & features) protected
Sets the weights of the nodes of tree according to the given features. Before calling this function, the nodes and the words must be already created (by calling HKmeansStep and createWords)
Parameters
features
Referenced by DBoW2::TemplatedVocabulary< TDescriptor, F >::Node::isLeaf().
setScoringType()
template<class TDescriptor , class F > void DBoW2::TemplatedVocabulary< TDescriptor, F >::setScoringType (ScoringType type)
Changes the scoring method
Parameters
type new scoring type
Referenced by DBoW2::TemplatedVocabulary< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::getScoringType().
setWeightingType()
template<class TDescriptor , class F > void DBoW2::TemplatedVocabulary< TDescriptor, F >::setWeightingType (WeightingType type) inline
Changes the weighting method
Parameters
type new weighting type
Referenced by DBoW2::TemplatedVocabulary< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::getScoringType().
size()
template<class TDescriptor , class F > unsigned int DBoW2::TemplatedVocabulary< TDescriptor, F >::size () const inline virtual
Returns the number of words in the vocabulary
Returns
number of words
Referenced by DBoW2::TemplatedVocabulary< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::createWords(), DBoW2::operator<<(), DBoW2::TemplatedVocabulary< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::setNodeWeights(), and DBoW2::TemplatedVocabulary< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::size().
stopWords()
template<class TDescriptor , class F > int DBoW2::TemplatedVocabulary< TDescriptor, F >::stopWords (double minWeight) virtual
Stops those words whose weight is below minWeight. Words are stopped by setting their weight to 0. There are not returned later when transforming image features into vectors. Note that when using IDF or TF_IDF, the weight is the idf part, which is equivalent to -log(f), where f is the frequency of the word (f = Ni/N, Ni: number of training images where the word is present, N: number of training images). Note that the old weight is forgotten, and subsequent calls to this function with a lower minWeight have no effect.
Returns
number of words stopped now
Referenced by DBoW2::TemplatedVocabulary< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::getScoringType().
transform() [1/5]
template<class TDescriptor, class F > void DBoW2::TemplatedVocabulary< TDescriptor, F >::transform (const std::vector< TDescriptor > & features, BowVector & v) const virtual
Transforms a set of descriptores into a bow vector
Parameters
features
v (out) bow vector of weighted words
Referenced by DBoW2::TemplatedVocabulary< TDescriptor, F >::Node::isLeaf().
transform() [2/5]
template<class TDescriptor, class F > void DBoW2::TemplatedVocabulary< TDescriptor, F >::transform (const std::vector< TDescriptor > & features, BowVector & v, FeatureVector & fv, int levelsup) const virtual
Transform a set of descriptors into a bow vector and a feature vector
Parameters
features
v (out) bow vector
fv (out) feature vector of nodes and feature indexes
levelsup levels to go up the vocabulary tree to get the node index
transform() [3/5]
template<class TDescriptor, class F > WordId DBoW2::TemplatedVocabulary< TDescriptor, F >::transform (const TDescriptor & feature) const virtual
Transforms a single feature into a word (without weight)
Parameters
feature
Returns
word id
transform() [4/5]
template<class TDescriptor, class F > void DBoW2::TemplatedVocabulary< TDescriptor, F >::transform (const TDescriptor & feature, WordId & id, WordValue & weight, NodeId * nid = NULL, int levelsup = 0) const protected virtual
Returns the word id associated to a feature
Parameters
feature
id (out) word id
weight (out) word weight
nid (out) if given, id of the node "levelsup" levels up
levelsup
transform() [5/5]
template<class TDescriptor, class F > void DBoW2::TemplatedVocabulary< TDescriptor, F >::transform (const TDescriptor & feature, WordId & id) const protected virtual
Returns the word id associated to a feature
Parameters
feature
id (out) word id
Member Data Documentation
m_words
template<class TDescriptor, class F> std::vector<Node*> DBoW2::TemplatedVocabulary< TDescriptor, F >::m_words protected
Words of the vocabulary (tree leaves) this condition holds: m_words[wid]->word_id == wid
The documentation for this class was generated from the following file:
pose_graph/src/ThirdParty/DBoW/TemplatedVocabulary.h