VINS MONO COMMENTED: DUtils::Random Class Reference
DUtils::Random Class Reference
Functions to generate pseudo-random numbers.
#include <Random.h>
Classes
class UnrepeatedRandomizer
Provides pseudo-random numbers with no repetitions.
Static Public Member Functions
static void SeedRand ()
static void SeedRandOnce ()
static void SeedRand (int seed)
static void SeedRandOnce (int seed)
template<class T >
static T RandomValue ()
template<class T >
static T RandomValue (T min, T max)
static int RandomInt (int min, int max)
template<class T >
static T RandomGaussianValue (T mean, T sigma)
Detailed Description
Functions to generate pseudo-random numbers.
Member Function Documentation
RandomGaussianValue()
template<class T > static T DUtils::Random::RandomGaussianValue (T mean, T sigma) inline static
Returns a random number from a gaussian distribution
Parameters
mean
sigma standard deviation
Referenced by DVision::BRIEF::generateTestPoints().
RandomInt()
int DUtils::Random::RandomInt (int min, int max) static
Returns a random int in the range [min..max]
Parameters
min
max
Returns
random int in [min..max]
Referenced by DUtils::Random::UnrepeatedRandomizer::get(), DBoW2::TemplatedVocabulary< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::initiateClustersKMpp(), and RandomValue().
RandomValue() [1/2]
template<class T > static T DUtils::Random::RandomValue () inline static
Returns a random number in the range [0..1]
Returns
random T number in [0..1]
RandomValue() [2/2]
template<class T > static T DUtils::Random::RandomValue (T min, T max) inline static
Returns a random number in the range [min..max]
Parameters
min
max
Returns
random T number in [min..max]
References RandomInt().
SeedRand() [1/2]
void DUtils::Random::SeedRand () static
Sets the random number seed to the current time
References DUtils::Timestamp::getFloatTime(), and DUtils::Timestamp::setToCurrentTime().
Referenced by SeedRandOnce().
SeedRand() [2/2]
void DUtils::Random::SeedRand (int seed) static
Sets the given random number seed
Parameters
seed
SeedRandOnce() [1/2]
void DUtils::Random::SeedRandOnce () static
Sets the random number seed to the current time only the first time this function is called
References SeedRand().
Referenced by DVision::BRIEF::generateTestPoints(), DUtils::Random::UnrepeatedRandomizer::get(), and DBoW2::TemplatedVocabulary< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::initiateClustersKMpp().
SeedRandOnce() [2/2]
void DUtils::Random::SeedRandOnce (int seed) static
Sets the given random number seed only the first time this function is called
Parameters
seed
References SeedRand().
The documentation for this class was generated from the following files:
pose_graph/src/ThirdParty/DUtils/Random.h
pose_graph/src/ThirdParty/DUtils/Random.cpp