VINS MONO COMMENTED: DBoW2::TemplatedDatabase< TDescriptor, F > Class Template Reference
DBoW2::TemplatedDatabase< TDescriptor, F > Class Template Reference
Generic Database.
#include <TemplatedDatabase.h>
Classes
struct IFPair
Item of IFRow.
Public Member Functions
TemplatedDatabase (bool use_di=true, int di_levels=0)
template<class T >
TemplatedDatabase (const T &voc, bool use_di=true, int di_levels=0)
TemplatedDatabase (const TemplatedDatabase< TDescriptor, F > &db)
TemplatedDatabase (const std::string &filename)
TemplatedDatabase (const char *filename)
virtual ~TemplatedDatabase (void)
TemplatedDatabase< TDescriptor, F > & operator= (const TemplatedDatabase< TDescriptor, F > &db)
template<class T >
void setVocabulary (const T &voc)
template<class T >
void setVocabulary (const T &voc, bool use_di, int di_levels=0)
const TemplatedVocabulary< TDescriptor, F > * getVocabulary () const
void allocate (int nd=0, int ni=0)
EntryId add (const std::vector< TDescriptor > &features, BowVector *bowvec=NULL, FeatureVector *fvec=NULL)
EntryId add (const BowVector &vec, const FeatureVector &fec=FeatureVector())
void delete_entry (const EntryId entry_id)
void clear ()
unsigned int size () const
bool usingDirectIndex () const
int getDirectIndexLevels () const
void query (const std::vector< TDescriptor > &features, QueryResults &ret, int max_results=1, int max_id=-1) const
void query (const BowVector &vec, QueryResults &ret, int max_results=1, int max_id=-1) const
const FeatureVector & retrieveFeatures (EntryId id) const
void save (const std::string &filename) const
void load (const std::string &filename)
virtual void save (cv::FileStorage &fs, const std::string &name="database") const
virtual void load (const cv::FileStorage &fs, const std::string &name="database")
Protected Types
typedef std::list< IFPair > IFRow
Row of InvertedFile.
typedef std::vector< IFRow > InvertedFile
Inverted index.
typedef std::vector< FeatureVector > DirectFile
Direct index.
Protected Member Functions
void queryL1 (const BowVector &vec, QueryResults &ret, int max_results, int max_id) const
Query with L1 scoring.
void queryL2 (const BowVector &vec, QueryResults &ret, int max_results, int max_id) const
Query with L2 scoring.
void queryChiSquare (const BowVector &vec, QueryResults &ret, int max_results, int max_id) const
Query with Chi square scoring.
void queryBhattacharyya (const BowVector &vec, QueryResults &ret, int max_results, int max_id) const
Query with Bhattacharyya scoring.
void queryKL (const BowVector &vec, QueryResults &ret, int max_results, int max_id) const
Query with KL divergence scoring.
void queryDotProduct (const BowVector &vec, QueryResults &ret, int max_results, int max_id) const
Query with dot product scoring.
Protected Attributes
TemplatedVocabulary< TDescriptor, F > * m_voc
Associated vocabulary.
bool m_use_di
Flag to use direct index.
int m_dilevels
InvertedFile m_ifile
Inverted file (must have size() == |words|)
DirectFile m_dfile
Direct file (resized for allocation)
std::vector< BowVector > m_dBowfile
int m_nentries
Number of valid entries in m_dfile.
Detailed Description
template<class TDescriptor, class F>
class DBoW2::TemplatedDatabase< TDescriptor, F >
Generic Database.
Parameters
TDescriptor class of descriptor
F class of descriptor functions
Constructor & Destructor Documentation
TemplatedDatabase() [1/5]
template<class TDescriptor , class F > DBoW2::TemplatedDatabase< TDescriptor, F >::TemplatedDatabase (bool use_di = true, int di_levels = 0) explicit
Creates an empty database without vocabulary
Parameters
use_di a direct index is used to store feature indexes
di_levels levels to go up the vocabulary tree to select the node id to store in the direct index when adding images
Referenced by DBoW2::TemplatedDatabase< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::TemplatedDatabase().
TemplatedDatabase() [2/5]
template<class TDescriptor , class F > template<class T > DBoW2::TemplatedDatabase< TDescriptor, F >::TemplatedDatabase (const T & voc, bool use_di = true, int di_levels = 0) explicit
Creates a database with the given vocabulary
Parameters
T class inherited from TemplatedVocabulary<TDescriptor, F>
voc vocabulary
use_di a direct index is used to store feature indexes
di_levels levels to go up the vocabulary tree to select the node id to store in the direct index when adding images
TemplatedDatabase() [3/5]
template<class TDescriptor, class F> DBoW2::TemplatedDatabase< TDescriptor, F >::TemplatedDatabase (const TemplatedDatabase< TDescriptor, F > & db)
Copy constructor. Copies the vocabulary too
Parameters
db object to copy
TemplatedDatabase() [4/5]
template<class TDescriptor, class F> DBoW2::TemplatedDatabase< TDescriptor, F >::TemplatedDatabase (const std::string & filename)
Creates the database from a file
Parameters
filename
TemplatedDatabase() [5/5]
template<class TDescriptor, class F> DBoW2::TemplatedDatabase< TDescriptor, F >::TemplatedDatabase (const char * filename)
Creates the database from a file
Parameters
filename
~TemplatedDatabase()
template<class TDescriptor , class F > DBoW2::TemplatedDatabase< TDescriptor, F >::~TemplatedDatabase (void) virtual
Destructor
Member Function Documentation
add() [1/2]
template<class TDescriptor, class F > EntryId DBoW2::TemplatedDatabase< TDescriptor, F >::add (const std::vector< TDescriptor > & features, BowVector * bowvec = NULL, FeatureVector * fvec = NULL)
Adds an entry to the database and returns its index
Parameters
features features of the new entry
bowvec if given, the bow vector of these features is returned
fvec if given, the vector of nodes and feature indexes is returned
Returns
id of new entry
Referenced by DBoW2::TemplatedDatabase< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::add().
add() [2/2]
template<class TDescriptor, class F > EntryId DBoW2::TemplatedDatabase< TDescriptor, F >::add (const BowVector & vec, const FeatureVector & fec = FeatureVector())
Adss an entry to the database and returns its index
Parameters
vec bow vector
fec feature vector to add the entry. Only necessary if using the direct index
Returns
id of new entry
allocate()
template<class TDescriptor , class F > void DBoW2::TemplatedDatabase< TDescriptor, F >::allocate (int nd = 0, int ni = 0)
Allocates some memory for the direct and inverted indexes
Parameters
nd number of expected image entries in the database
ni number of expected words per image
Note
Use 0 to ignore a parameter
clear()
template<class TDescriptor , class F > void DBoW2::TemplatedDatabase< TDescriptor, F >::clear (void) inline
Empties the database
Referenced by DBoW2::TemplatedDatabase< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::load(), DBoW2::TemplatedDatabase< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::setVocabulary(), and DBoW2::TemplatedDatabase< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::TemplatedDatabase().
getDirectIndexLevels()
template<class TDescriptor , class F > int DBoW2::TemplatedDatabase< TDescriptor, F >::getDirectIndexLevels () const inline
Returns the di levels when using direct index
Returns
di levels
Referenced by DBoW2::operator<<().
getVocabulary()
template<class TDescriptor , class F > const TemplatedVocabulary< TDescriptor, F > * DBoW2::TemplatedDatabase< TDescriptor, F >::getVocabulary () const inline
Returns a pointer to the vocabulary used
Returns
vocabulary
Referenced by DBoW2::operator<<().
load() [1/2]
template<class TDescriptor , class F > void DBoW2::TemplatedDatabase< TDescriptor, F >::load (const std::string & filename)
Loads the database from a file
Parameters
filename
Referenced by DBoW2::TemplatedDatabase< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::load(), and DBoW2::TemplatedDatabase< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::TemplatedDatabase().
load() [2/2]
template<class TDescriptor , class F > void DBoW2::TemplatedDatabase< TDescriptor, F >::load (const cv::FileStorage & fs, const std::string & name = "database") virtual
Loads the database from the given file storage structure
Parameters
fs
name node name
operator=()
template<class TDescriptor, class F> TemplatedDatabase< TDescriptor, F > & DBoW2::TemplatedDatabase< TDescriptor, F >::operator= (const TemplatedDatabase< TDescriptor, F > & db)
Copies the given database and its vocabulary
Parameters
db database to copy
query() [1/2]
template<class TDescriptor, class F > void DBoW2::TemplatedDatabase< TDescriptor, F >::query (const std::vector< TDescriptor > & features, QueryResults & ret, int max_results = 1, int max_id = -1) const
Queries the database with some features
Parameters
features query features
ret (out) query results
max_results number of results to return. <= 0 means all
max_id only entries with id <= max_id are returned in ret. < 0 means all
Referenced by DBoW2::TemplatedDatabase< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::query().
query() [2/2]
template<class TDescriptor, class F > void DBoW2::TemplatedDatabase< TDescriptor, F >::query (const BowVector & vec, QueryResults & ret, int max_results = 1, int max_id = -1) const
Queries the database with a vector
Parameters
vec bow vector already normalized
ret results
max_results number of results to return. <= 0 means all
max_id only entries with id <= max_id are returned in ret. < 0 means all
retrieveFeatures()
template<class TDescriptor , class F > const FeatureVector & DBoW2::TemplatedDatabase< TDescriptor, F >::retrieveFeatures (EntryId id) const
Returns the a feature vector associated with a database entry
Parameters
id entry id (must be < size())
Returns
const reference to map of nodes and their associated features in the given entry
Referenced by DBoW2::TemplatedDatabase< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::queryDotProduct().
save() [1/2]
template<class TDescriptor , class F > void DBoW2::TemplatedDatabase< TDescriptor, F >::save (const std::string & filename) const
Stores the database in a file
Parameters
filename
Referenced by DBoW2::TemplatedDatabase< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::save().
save() [2/2]
template<class TDescriptor , class F > void DBoW2::TemplatedDatabase< TDescriptor, F >::save (cv::FileStorage & fs, const std::string & name = "database") const virtual
Stores the database in the given file storage structure
Parameters
fs
name node name
setVocabulary() [1/2]
template<class TDescriptor , class F > template<class T > void DBoW2::TemplatedDatabase< TDescriptor, F >::setVocabulary (const T & voc) inline
Sets the vocabulary to use and clears the content of the database.
Parameters
T class inherited from TemplatedVocabulary<TDescriptor, F>
voc vocabulary to copy
Referenced by DBoW2::TemplatedDatabase< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::add(), DBoW2::TemplatedDatabase< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::operator=(), DBoW2::TemplatedDatabase< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::setVocabulary(), and DBoW2::TemplatedDatabase< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::TemplatedDatabase().
setVocabulary() [2/2]
template<class TDescriptor , class F > template<class T > void DBoW2::TemplatedDatabase< TDescriptor, F >::setVocabulary (const T & voc, bool use_di, int di_levels = 0) inline
Sets the vocabulary to use and the direct index parameters, and clears the content of the database
Parameters
T class inherited from TemplatedVocabulary<TDescriptor, F>
voc vocabulary to copy
use_di a direct index is used to store feature indexes
di_levels levels to go up the vocabulary tree to select the node id to store in the direct index when adding images
size()
template<class TDescriptor , class F > unsigned int DBoW2::TemplatedDatabase< TDescriptor, F >::size () const inline
Returns the number of entries in the database
Returns
number of entries in the database
Referenced by DBoW2::operator<<(), and DBoW2::TemplatedDatabase< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::retrieveFeatures().
usingDirectIndex()
template<class TDescriptor , class F > bool DBoW2::TemplatedDatabase< TDescriptor, F >::usingDirectIndex () const inline
Checks if the direct index is being used
Returns
true iff using direct index
Referenced by DBoW2::operator<<().
Member Data Documentation
m_dilevels
template<class TDescriptor, class F> int DBoW2::TemplatedDatabase< TDescriptor, F >::m_dilevels protected
Levels to go up the vocabulary tree to select nodes to store in the direct index
Referenced by DBoW2::TemplatedDatabase< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::add(), DBoW2::TemplatedDatabase< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::getDirectIndexLevels(), DBoW2::TemplatedDatabase< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::load(), DBoW2::TemplatedDatabase< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::operator=(), DBoW2::TemplatedDatabase< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::save(), and DBoW2::TemplatedDatabase< DBoW2::FBrief::TDescriptor, DBoW2::FBrief >::setVocabulary().
The documentation for this class was generated from the following file:
pose_graph/src/ThirdParty/DBoW/TemplatedDatabase.h