VINS MONO COMMENTED: camodocal::PinholeCamera Class Reference
camodocal::PinholeCamera Class Reference
Classes
class Parameters
Public Member Functions
PinholeCamera ()
Construct a new Pinhole Camera:: Pinhole Camera object.
PinholeCamera (const std::string &cameraName, int imageWidth, int imageHeight, double k1, double k2, double p1, double p2, double fx, double fy, double cx, double cy)
Constructor from the projection model parameters.
PinholeCamera (const Parameters &params)
Constructor from the projection model parameters.
Camera::ModelType modelType (void) const
virtual type of function modelType
const std::string & cameraName (void) const
virtual type of funtion cameraName
int imageWidth (void) const
virtual type of function imageWidth
int imageHeight (void) const
virtual type of function imageHeight
void estimateIntrinsics (const cv::Size &boardSize, const std::vector< std::vector< cv::Point3f > > &objectPoints, const std::vector< std::vector< cv::Point2f > > &imagePoints)
virtual function of camera intrinsics
virtual void liftSphere (const Eigen::Vector2d &p, Eigen::Vector3d &P) const
Lifts a point from the image plane to the unit sphere.
void liftProjective (const Eigen::Vector2d &p, Eigen::Vector3d &P) const
Lifts a point from the image plane to its projective ray.
void spaceToPlane (const Eigen::Vector3d &P, Eigen::Vector2d &p) const
Project a 3D point (x,y,z) to the image plane in (u,v)
void spaceToPlane (const Eigen::Vector3d &P, Eigen::Vector2d &p, Eigen::Matrix< double, 2, 3 > &J) const
void undistToPlane (const Eigen::Vector2d &p_u, Eigen::Vector2d &p) const
Projects an undistorted 2D point p_u to the image plane.
void distortion (const Eigen::Vector2d &p_u, Eigen::Vector2d &d_u) const
Apply distortion to input point (from the normalised plane)
void distortion (const Eigen::Vector2d &p_u, Eigen::Vector2d &d_u, Eigen::Matrix2d &J) const
Apply distortion to input point (from the normalised plane) and calculate Jacobian.
void initUndistortMap (cv::Mat &map1, cv::Mat &map2, double fScale=1.0) const
cv::Mat initUndistortRectifyMap (cv::Mat &map1, cv::Mat &map2, float fx=-1.0f, float fy=-1.0f, cv::Size imageSize=cv::Size(0, 0), float cx=-1.0f, float cy=-1.0f, cv::Mat rmat=cv::Mat::eye(3, 3, CV_32F)) const
int parameterCount (void) const
pure virtual function of parameter count
const Parameters & getParameters (void) const
void setParameters (const Parameters &parameters)
void readParameters (const std::vector< double > &parameterVec)
pure virtual function of reading parameters
void writeParameters (std::vector< double > &parameterVec) const
pure virtual function of writing parameters
void writeParametersToYamlFile (const std::string &filename) const
pure virtual function of writing parameters to YAML file
std::string parametersToString (void) const
pure virtual of converting parameters to string
Public Member Functions inherited from camodocal::Camera
virtual cv::Mat & mask (void)
virtual function of image Mask
virtual const cv::Mat & mask (void) const
virtual function of image Mask
virtual void estimateExtrinsics (const std::vector< cv::Point3f > &objectPoints, const std::vector< cv::Point2f > &imagePoints, cv::Mat &rvec, cv::Mat &tvec) const
calculate extrinsics with unit intrinsics
double reprojectionDist (const Eigen::Vector3d &P1, const Eigen::Vector3d &P2) const
Calculates the reprojection distance between points.
double reprojectionError (const std::vector< std::vector< cv::Point3f > > &objectPoints, const std::vector< std::vector< cv::Point2f > > &imagePoints, const std::vector< cv::Mat > &rvecs, const std::vector< cv::Mat > &tvecs, cv::OutputArray perViewErrors=cv::noArray()) const
calculate average reprojection error of all points in all frames (total error divede by total points) with 3D points and 2D points
double reprojectionError (const Eigen::Vector3d &P, const Eigen::Quaterniond &camera_q, const Eigen::Vector3d &camera_t, const Eigen::Vector2d &observed_p) const
calculate reprojection error of one 3D point with camera pose P & Q
void projectPoints (const std::vector< cv::Point3f > &objectPoints, const cv::Mat &rvec, const cv::Mat &tvec, std::vector< cv::Point2f > &imagePoints) const
project 3D points to 2d plane
Static Public Member Functions
template<typename T >
static void spaceToPlane (const T *const params, const T *const q, const T *const t, const Eigen::Matrix< T, 3, 1 > &P, Eigen::Matrix< T, 2, 1 > &p)
Additional Inherited Members
Public Types inherited from camodocal::Camera
enum ModelType { KANNALA_BRANDT, MEI, PINHOLE, SCARAMUZZA }
enumerate variable of camera model
Protected Attributes inherited from camodocal::Camera
cv::Mat m_mask
image mask
Constructor & Destructor Documentation
PinholeCamera() [1/2]
camodocal::PinholeCamera::PinholeCamera (const std::string & cameraName, int imageWidth, int imageHeight, double k1, double k2, double p1, double p2, double fx, double fy, double cx, double cy)
Constructor from the projection model parameters.
Construct a new Pinhole Camera:: Pinhole Camera object.
Parameters
cameraName name of camera
imageWidth width of current image
imageHeight height of current image
k1 distortion parameter
k2 distortion parameter
p1 distortion parameter
p2 distortion parameter
fx projection parameter
fy projection parameter
cx projection parameter
cy projection parameter
PinholeCamera() [2/2]
camodocal::PinholeCamera::PinholeCamera (const Parameters & params)
Constructor from the projection model parameters.
Construct a new Pinhole Camera:: Pinhole Camera object.
Parameters
params PinholeCamera::Parameters object
Member Function Documentation
distortion() [1/2]
void camodocal::PinholeCamera::distortion (const Eigen::Vector2d & p_u, Eigen::Vector2d & d_u) const
Apply distortion to input point (from the normalised plane)
Parameters
p_u undistorted coordinates of point on the normalised plane
Returns
to obtain the distorted point: p_d = p_u + d_u
Referenced by liftProjective(), spaceToPlane(), and undistToPlane().
distortion() [2/2]
void camodocal::PinholeCamera::distortion (const Eigen::Vector2d & p_u, Eigen::Vector2d & d_u, Eigen::Matrix2d & J) const
Apply distortion to input point (from the normalised plane) and calculate Jacobian.
Parameters
p_u undistorted coordinates of point on the normalised plane
Returns
to obtain the distorted point: p_d = p_u + d_u
References camodocal::Camera::Parameters::imageHeight(), camodocal::Camera::Parameters::imageWidth(), and spaceToPlane().
liftProjective()
void camodocal::PinholeCamera::liftProjective (const Eigen::Vector2d & p, Eigen::Vector3d & P) const virtual
Lifts a point from the image plane to its projective ray.
Parameters
p image coordinates
P coordinates of the projective ray
Implements camodocal::Camera.
References distortion().
Referenced by liftSphere().
liftSphere()
void camodocal::PinholeCamera::liftSphere (const Eigen::Vector2d & p, Eigen::Vector3d & P) const virtual
Lifts a point from the image plane to the unit sphere.
Parameters
p image coordinates
P coordinates of the point on the sphere
Implements camodocal::Camera.
References liftProjective().
spaceToPlane()
void camodocal::PinholeCamera::spaceToPlane (const Eigen::Vector3d & P, Eigen::Vector2d & p) const virtual
Project a 3D point (x,y,z) to the image plane in (u,v)
Parameters
P 3D point coordinates
p return value, contains the image point coordinates
Implements camodocal::Camera.
References distortion().
Referenced by distortion().
undistToPlane()
void camodocal::PinholeCamera::undistToPlane (const Eigen::Vector2d & p_u, Eigen::Vector2d & p) const virtual
Projects an undistorted 2D point p_u to the image plane.
Parameters
p_u 2D point coordinates
Returns
image point coordinates
Implements camodocal::Camera.
References distortion().
The documentation for this class was generated from the following files:
camera_model/include/camodocal/camera_models/PinholeCamera.h
camera_model/src/camera_models/PinholeCamera.cc