VINS MONO COMMENTED: DBoW2 Namespace Reference
DBoW2 Namespace Reference
Includes all the data structures to manage vocabularies and image databases.
Classes
class BowVector
Vector of words to represent images.
class FBrief
Functions to manipulate BRIEF descriptors.
class FClass
Generic class to encapsulate functions to manage descriptors.
class FeatureVector
Vector of nodes with indexes of local features.
class GeneralScoring
Base class of scoring functions.
class QueryResults
Multiple results from a query.
class Result
Single result of a query.
class TemplatedDatabase
Generic Database.
class TemplatedVocabulary
Generic Vocabulary.
Typedefs
typedef unsigned int WordId
Id of words.
typedef double WordValue
Value of a word.
typedef unsigned int NodeId
Id of nodes in the vocabulary treee.
typedef unsigned int EntryId
Id of entries of the database.
Enumerations
enum LNorm { L1, L2 }
L-norms for normalization.
enum WeightingType { TF_IDF, TF, IDF, BINARY }
Weighting type.
enum ScoringType {
L1_NORM, L2_NORM, CHI_SQUARE, KL,
BHATTACHARYYA, DOT_PRODUCT
}
Scoring type.
Functions
std::ostream & operator<< (std::ostream &out, const BowVector &v)
std::ostream & operator<< (std::ostream &out, const FeatureVector &v)
ostream & operator<< (ostream &os, const Result &ret)
ostream & operator<< (ostream &os, const QueryResults &ret)
class __SCORING_CLASS (L1Scoring, true, L1)
L1 Scoring object.
class __SCORING_CLASS (L2Scoring, true, L2)
L2 Scoring object.
class __SCORING_CLASS (ChiSquareScoring, true, L1)
Chi square Scoring object.
class __SCORING_CLASS (KLScoring, true, L1)
KL divergence Scoring object.
class __SCORING_CLASS (BhattacharyyaScoring, true, L1)
Bhattacharyya Scoring object.
class __SCORING_CLASS (DotProductScoring, false, L1)
Dot product Scoring object.
template<class TDescriptor , class F >
std::ostream & operator<< (std::ostream &os, const TemplatedDatabase< TDescriptor, F > &db)
template<class TDescriptor , class F >
std::ostream & operator<< (std::ostream &os, const TemplatedVocabulary< TDescriptor, F > &voc)
Detailed Description
Includes all the data structures to manage vocabularies and image databases.
File: BowVector.cpp Date: March 2011 Author: Dorian Galvez-Lopez Description: bag of words vector License: see the LICENSE.txt file
File: BowVector.h Date: March 2011 Author: Dorian Galvez-Lopez Description: bag of words vector License: see the LICENSE.txt file
File: FBrief.h Date: November 2011 Author: Dorian Galvez-Lopez Description: functions for BRIEF descriptors License: see the LICENSE.txt file
File: FClass.h Date: November 2011 Author: Dorian Galvez-Lopez Description: generic FClass to instantiate templated classes License: see the LICENSE.txt file
File: FeatureVector.cpp Date: November 2011 Author: Dorian Galvez-Lopez Description: feature vector License: see the LICENSE.txt file
File: FeatureVector.h Date: November 2011 Author: Dorian Galvez-Lopez Description: feature vector License: see the LICENSE.txt file
File: QueryResults.h Date: March, November 2011 Author: Dorian Galvez-Lopez Description: structure to store results of database queries License: see the LICENSE.txt file
File: ScoringObject.h Date: November 2011 Author: Dorian Galvez-Lopez Description: functions to compute bow scores License: see the LICENSE.txt file
File: TemplatedDatabase.h Date: March 2011 Author: Dorian Galvez-Lopez Description: templated database of images License: see the LICENSE.txt file
File: TemplatedVocabulary.h Date: February 2011 Author: Dorian Galvez-Lopez Description: templated vocabulary License: see the LICENSE.txt file
Function Documentation
operator<<() [1/4]
std::ostream& DBoW2::operator<< (std::ostream & out, const FeatureVector & v)
Sends a string versions of the feature vector through the stream
Parameters
out stream
v feature vector
operator<<() [2/4]
std::ostream& DBoW2::operator<< (std::ostream & out, const BowVector & v)
Prints the content of the bow vector
Parameters
out stream
v
operator<<() [3/4]
template<class TDescriptor , class F > std::ostream& DBoW2::operator<< (std::ostream & os, const TemplatedDatabase< TDescriptor, F > & db)
Writes printable information of the database
Parameters
os stream to write to
db
References DBoW2::TemplatedDatabase< TDescriptor, F >::getDirectIndexLevels(), DBoW2::TemplatedDatabase< TDescriptor, F >::getVocabulary(), DBoW2::TemplatedDatabase< TDescriptor, F >::size(), and DBoW2::TemplatedDatabase< TDescriptor, F >::usingDirectIndex().
operator<<() [4/4]
template<class TDescriptor , class F > std::ostream& DBoW2::operator<< (std::ostream & os, const TemplatedVocabulary< TDescriptor, F > & voc)
Writes printable information of the vocabulary
Parameters
os stream to write to
voc
References DBoW2::TemplatedVocabulary< TDescriptor, F >::getBranchingFactor(), DBoW2::TemplatedVocabulary< TDescriptor, F >::getDepthLevels(), DBoW2::TemplatedVocabulary< TDescriptor, F >::getScoringType(), DBoW2::TemplatedVocabulary< TDescriptor, F >::getWeightingType(), and DBoW2::TemplatedVocabulary< TDescriptor, F >::size().