VINS MONO COMMENTED: DBoW2::TemplatedVocabulary< TDescriptor, F >::Node Struct Reference
DBoW2::TemplatedVocabulary< TDescriptor, F >::Node Struct Reference
Tree node.
#include <TemplatedVocabulary.h>
Public Member Functions
Node ()
Node (NodeId _id)
bool isLeaf () const
Public Attributes
NodeId id
Node id.
WordValue weight
Weight if the node is a word.
std::vector< NodeId > children
Children.
NodeId parent
Parent node (undefined in case of root)
TDescriptor descriptor
Node descriptor.
WordId word_id
Word id if the node is a word.
Detailed Description
template<class TDescriptor, class F>
struct DBoW2::TemplatedVocabulary< TDescriptor, F >::Node
Tree node.
Constructor & Destructor Documentation
Node() [1/2]
template<class TDescriptor, class F> DBoW2::TemplatedVocabulary< TDescriptor, F >::Node::Node () inline
Empty constructor
Node() [2/2]
template<class TDescriptor, class F> DBoW2::TemplatedVocabulary< TDescriptor, F >::Node::Node (NodeId _id) inline
Constructor
Parameters
_id node id
Member Function Documentation
isLeaf()
template<class TDescriptor, class F> bool DBoW2::TemplatedVocabulary< TDescriptor, F >::Node::isLeaf () const inline
Returns whether the node is a leaf node
Returns
true iff the node is a leaf
References DBoW2::TemplatedVocabulary< TDescriptor, F >::createScoringObject(), DBoW2::TemplatedVocabulary< TDescriptor, F >::createWords(), DBoW2::TemplatedVocabulary< TDescriptor, F >::getFeatures(), DBoW2::TemplatedVocabulary< TDescriptor, F >::HKmeansStep(), DBoW2::TemplatedVocabulary< TDescriptor, F >::initiateClusters(), DBoW2::TemplatedVocabulary< TDescriptor, F >::initiateClustersKMpp(), DBoW2::TemplatedVocabulary< TDescriptor, F >::setNodeWeights(), DBoW2::TemplatedVocabulary< TDescriptor, F >::transform(), and DBoW2::TemplatedVocabulary< TDescriptor, F >::Node::weight.
The documentation for this struct was generated from the following file:
pose_graph/src/ThirdParty/DBoW/TemplatedVocabulary.h